### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by pep248** [ros2-gbp/ros2-gbp-github-org#631]
* Name of the new release team: ikerlan_ker
* Release repositories to add:
  

  * [FIRST_REPOSITORY](SOURCE URL)
    * [ros/rosdistro source entry](https://github.com/Ikerlan-KER/rosdistro/blob/ba069c6cbecbe990b52ab2baa5e52bc5b7244401/humble/distribution.yaml#L2231C1-L2239C23)
    * [x] There is an existing release repository which should be imported: https://github.com/Ikerlan-KER/extrinsic_calibrator
We are currently waiting the [pull request](https://github.com/ros/rosdistro/pull/43284) approval.

* Team members
  * [@pep248](https://github.com/Ikerlan-KER/extrinsic_calibrator/blob/main/extrinsic_calibrator_core/package.xml)
  * [@agonzat](https://github.com/Ikerlan-KER/extrinsic_calibrator/blob/main/extrinsic_calibrator_core/package.xml)

**Comment by nuclearsandwich** [comment]
@pep248 can you please link to a merged rosdistro PR for the rosdistro source entry. Your current link is in a fork and therefore not valid evidence that the change has been merged.

**Comment by pep248** [comment]
> @pep248 can you please link to a merged rosdistro PR for the rosdistro source entry. Your current link is in a fork and therefore not valid evidence that the change has been merged.

https://github.com/ros/rosdistro/pull/43284

We are waiting for the pull-request to be accepted.

We will provide the link you requested as soon as we are accepted.

**Comment by pep248** [comment]
It has been approved:
https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml

```
  extrinsic_calibrator:
    doc:
      type: git
      url: https://github.com/Ikerlan-KER/extrinsic_calibrator.git
      version: humble
    source:
      type: git
      url: https://github.com/Ikerlan-KER/extrinsic_calibrator.git
      version: humble
    status: maintained
```
